<a href="https://colab.research.google.com/github/Nashwin9/GreatLakes/blob/master/Computer_Vision_With_CNN_R7_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The points distribution for this case is as follows:

1. Read the images and generate the train and test dataset (5 points)
2. Divide the data set into Train and validation data sets
3. Initialize & build the model (10 points)
4. Optimize the model (5 points)
5. Predict the accuracy for both train and validation data (5 points)

In [0]:
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [3]:
!ls

drive  sample_data


In [0]:
project_path='/content/drive/My Drive/Computer Vision/'

In [0]:
train_path= project_path + 'train.zip'
test_path=project_path + 'test.zip'

In [0]:
from zipfile import ZipFile
with ZipFile(train_path,'r') as f:
  f.extractall()

In [0]:
 from zipfile import ZipFile
with ZipFile(test_path,'r') as f:
  f.extractall()

In [0]:
import os

In [0]:
x_train= []
y_train=[]
import os

In [0]:
os.chdir(project_path)

In [11]:
os.listdir()

['sample_submission.csv', 'test.zip', 'train.zip', 'train', 'test']

In [0]:
os.chdir(project_path+'train/')

In [13]:
os.listdir()

['Fat Hen',
 'Small-flowered Cranesbill',
 'Cleavers',
 'Black-grass',
 'Sugar beet',
 'Shepherds Purse',
 'Charlock',
 'Loose Silky-bent',
 'Scentless Mayweed',
 'Maize',
 'Common Chickweed',
 'Common wheat']

In [0]:
import cv2

In [15]:
for i in os.listdir():
  print(i)
  for j in os.listdir(i):
    temp = cv2.imread(project_path+'train/'+i+'/'+j)
    temp = cv2.resize(temp,(128,128))
    x_train.append(temp)
    y_train.append(i)


Fat Hen
Small-flowered Cranesbill
Cleavers
Black-grass
Sugar beet
Shepherds Purse
Charlock
Loose Silky-bent
Scentless Mayweed
Maize
Common Chickweed
Common wheat


In [16]:
x_train[0].shape

(128, 128, 3)

In [0]:
import pandas as pd
dum = pd.get_dummies(y_train)

In [0]:
encoded_labels = dum
y_train = dum

In [0]:
import numpy as np
y_train = np.array(y_train)

In [0]:
x_train = np.array(x_train)

In [21]:
x_train[0].shape

(128, 128, 3)

In [22]:
from sklearn.model_selection import train_test_split
x_train2, x_val, y_train2, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=2)
print (len(x_train2))
print (len(x_val))

3800
950


In [23]:
x_train2[0].shape

(128, 128, 3)

In [0]:
#x_train = np.array(x_train)

In [0]:
x_train2 = x_train2.reshape(x_train2.shape[0],128,128,3)

In [0]:
x_train2 = np.array(x_train2)

In [37]:
x_train2.shape

(3800, 128, 128, 3)

In [25]:
x_val.shape[0]

950

In [0]:
x_val = x_val.reshape(x_val.shape[0],128,128,3)

In [27]:
print (x_train2.shape)
print (x_val.shape)

(3800, 128, 128, 3)
(950, 128, 128, 3)


In [28]:
print(y_train2.shape)
print(y_val.shape)

(3800, 12)
(950, 12)


In [29]:
from keras.models import Sequential
from keras.layers import Convolution2D, Dropout, Dense

Using TensorFlow backend.


In [0]:
from keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.optimizers import adam

In [31]:
model = Sequential()
model.add(BatchNormalization(input_shape = (128,128,3)))
model.add(Convolution2D(32, (3,3), activation ='relu', input_shape = (128, 128, 3))) 
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=64, kernel_size=4, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=128, kernel_size=2, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Flatten()) 

# fully connected layer
model.add(Dense(units=128,activation = 'relu'))
model.add(Dense(units = 64, activation = 'relu'))
#model.add(Dropout(0.3))
model.add(Dense(units = 32, activation = 'relu'))
#model.add(Dropout(0.3))
model.add(Dense(units = 12, activation = 'softmax')) 


Instructions for updating:
Colocations handled automatically by placer.


In [0]:
optimizer = adam(lr=0.001)
model.compile(optimizer='adam', loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [33]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_1 (Batch (None, 128, 128, 3)       12        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 126, 126, 32)      896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 63, 63, 64)        32832     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 31, 31, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 31, 31, 128)       73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 15, 15, 128)       0         
__________

In [39]:
batch_size = 64
nb_epochs = 10
history = model.fit(x_train2,y_train2,
                    epochs=20, 
                    validation_data=(x_val,y_val),
                    verbose = 1,
                    initial_epoch=0)

Train on 3800 samples, validate on 950 samples
Epoch 1/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0284 - acc: 0.9913 - val_loss: 0.0148 - val_acc: 0.9947
Epoch 2/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0463 - acc: 0.9866 - val_loss: 0.0604 - val_acc: 0.9768
Epoch 3/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0344 - acc: 0.9900 - val_loss: 0.0446 - val_acc: 0.9842
Epoch 4/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0550 - acc: 0.9839 - val_loss: 0.0813 - val_acc: 0.9779
Epoch 5/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0914 - acc: 0.9742 - val_loss: 0.0220 - val_acc: 0.9926
Epoch 6/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0108 - acc: 0.9987 - val_loss: 0.0132 - val_acc: 0.9958
Epoch 7/20
3800/3800 [==============================] - 8s 2ms/step - loss: 0.0032 - acc: 0.9989 - val_loss: 0.0440 - val_acc: 0.9874
Epoch 8/20
3800

In [40]:
print(model.evaluate(x_train2, y_train2))  # Evaluate on train set
print(model.evaluate(x_val, y_val))  # Evaluate on val set

3800/3800 [==============================] - 3s 717us/step
[0.04018772741093447, 0.988421052631579]
950/950 [==============================] - 1s 675us/step
[0.2418935914729771, 0.9284210522551286]


In [41]:
from sklearn.metrics import confusion_matrix

# PREDICTIONS on val
y_pred = model.predict(x_val)
y_class = np.argmax(y_pred, axis = 1) 
y_check = np.argmax(y_val, axis = 1) 

cmatrix = confusion_matrix(y_check, y_class)
print(cmatrix)

[[ 36   0   0   0   3   0  13   0   0   0   0   0]
 [  0  70   0   0   0   0   0   0   0   0   0   0]
 [  0   0  50   0   0   0   0   0   0   0   0   0]
 [  0   0   0 117   0   0   0   0   0   0   1   0]
 [  0   1   2   0  43   0   0   0   1   0   0   0]
 [  0   2   0   1   0  96   0   0   1   0   2   0]
 [ 16   0   0   0   7   1 106   0   4   0   0   0]
 [  0   0   0   0   0   0   0  39   1   0   0   0]
 [  0   0   0   0   0   0   0   1  88   1   0   0]
 [  0   0   0   1   0   1   0   0   2  45   0   0]
 [  0   1   0   0   0   0   0   0   0   0 111   0]
 [  0   1   1   1   0   0   0   0   2   0   0  81]]


In [43]:
print(project_path)

/content/drive/My Drive/Computer Vision/


In [0]:
x_test= []
y_test=[]
import os

In [0]:
os.chdir(project_path)

In [0]:
os.chdir(project_path+'test/')

In [49]:
os.listdir()

['c0461776c.png',
 '4bbfd1e05.png',
 '1d0cbd819.png',
 '93079d970.png',
 '856f2910a.png',
 '976e4e079.png',
 'b31292706.png',
 '29bab7cad.png',
 '37297a64c.png',
 'f2dc546ca.png',
 'b6a3f7876.png',
 '8874bba69.png',
 '1459e96a0.png',
 '9a3f20121.png',
 '5315c2dca.png',
 'b7a7f6390.png',
 '20e562fd5.png',
 'e3f50adfc.png',
 '6ba4ef411.png',
 'acdb75e00.png',
 'e0ec5b6a1.png',
 '219fd68d5.png',
 '41f1c3cdb.png',
 '8c98a6e9b.png',
 '1bf9b94a6.png',
 'cadab6616.png',
 '17d5e5ac4.png',
 'aee6fa3df.png',
 '7e9cf1c46.png',
 '19618ad6a.png',
 '48231e475.png',
 '1c52ea820.png',
 '3b73c3b61.png',
 '33448fe39.png',
 '19b51843a.png',
 '4e1190d78.png',
 '0c45ace27.png',
 '851c90831.png',
 'd93c7ab6d.png',
 '279df95f2.png',
 '534e74d83.png',
 'ace8761dd.png',
 '7615e52d3.png',
 '71b232519.png',
 'c7ae30f3a.png',
 'fd87b36ae.png',
 '7f46a71db.png',
 'a276c65f7.png',
 'd84d37a61.png',
 '3d67c434b.png',
 '1f5e5554e.png',
 'c6c8d4ba0.png',
 '0ad9e7dfb.png',
 '1f3f44563.png',
 'bffc08672.png',
 'e82017ba

In [57]:
if (os.path.isdir()):
   for i in os.listdir():
  
     try:
    dummy1 = cv2.imread(project_path+'test/'+i)
    dummy1 = cv2.resize(dummy,(128,128))
    x_test.append(dummy1)
    y_test.append(i)
    

IndentationError: ignored

In [59]:
path_to_test = project_path+'test/*.png'
pics = glob(path_to_test)

testimages = []
tests = []
count=1
num = len(pics)

for i in pics:
    print(str(count)+'/'+str(num),end='\r')
    tests.append(i.split('/')[-1])
    testimages.append(cv2.resize(cv2.imread(i),(128,128)))
    count = count + 1

testimages = np.asarray(testimages)

In [60]:
testimages.shape

(794, 128, 128, 3)

In [67]:
from sklearn import preprocessing
from keras.utils import np_utils
labels = preprocessing.LabelEncoder()
labels.fit(y_train[0])
print('Classes'+str(labels.classes_))
encodedlabels = labels.transform(y_train[0])
clearalllabels = np_utils.to_categorical(encodedlabels)
classes = clearalllabels.shape[1]
print(str(classes))
x_train[0].value_counts().plot(kind='pie')


Classes[0 1]
2


AttributeError: ignored

In [0]:
submit = model.predict(testimages)
# PREDICTION TO A CSV FILE
pred = np.argmax(submit,axis=1)
predStr = labels.classes_[pred]
result = {'file':tests,'species':predStr}
result = pd.DataFrame(result)
result.to_csv("Prediction.csv",index=False)